version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - cd frontend
      - npm run build

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'

